name: dotnet-push
description: "Pushing the Dotnet packages to Github Packages"

inputs:  
  projects:
    description: The json array list of projects
    required: true  
  access-token: 
    description: 'The personal Access token passed from the calling flow'
    required: true
  azure-access-token: 
    description: 'The Azure Access token passed from the calling flow'
    required: true

runs:
  using: "composite"
  steps:
    - name: Push Nuget Package to GitHub packages feed
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        listOfProjects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')
        echo $listOfProjects        
        for project in $listOfProjects
        do
          echo "Pushing project: $project"          
          (cd $project; dotnet nuget push **/*.nupkg -k ${{inputs.access-token}} --source "https://nuget.pkg.github.com/aminjafer-n3o/index.json" --skip-duplicate )          
        done    

    - name: Push Nuget packages to Azure Artifacts 
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        listOfProjects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')        
        for project in $listOfProjects
        do
          echo "Pushing project: $project"          
          (cd $project; dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ inputs.azure-access-token }} --source "https://pkgs.dev.azure.com/n3oltd/_packaging/Feed/nuget/v3/index.json" )          
        done   

      
      