name: dotnet-build
description: "Restore Packages and build"

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore dependencies
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: dotnet restore --no-cache -v m      

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        dotnet nuget update source n3oltd -u n3oltd -p ${{inputs.access-token}}
        dotnet nuget list source
        packageVersion=$(date +"%Y.%m.%d")-${{ github.run_number }}     
        echo "Package Version: $packageVersion"
        dotnet build --no-restore -c Release /property:Version=$packageVersion


  