name: dotnet-pack
description: "Packing Dotnet project"

inputs:
  client-directories:
    description: The json array list of client directories
    required: true  
  access-token:
    description: the access token from the calling workflow
    required: true
  azure-feed-token:
    description: The Azure feed PAT
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse JSON client directories list input and then publish packages in a loop
      id: parse-json
      shell: bash
      run: |
        listOfDirectories=$(echo '${{ inputs.client-directories }}' | jq -c -r '.[]')                
        for packageDirectory in $listOfDirectories        
        do
          packageVersion=$(date +"%Y.%m.%d")-${{ github.run_number }}                 
          ( cd $packageDirectory; npm version $packageVersion; echo "//npm.pkg.github.com/:_authToken=${{ inputs.access-token }}" >> .npmrc; echo "@aminjafer-n3o:registry=https://npm.pkg.github.com" >> .npmrc; ls -a; npm publish)                                 
          ( cd $packageDirectory; rm .npmrc; 
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/:username=a2658dbf-ef4b-4609-9d8d-9c65c96f86a4" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/:_password=${{ inputs.azure-feed-token }}" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/:email=n3oltd@n3oltd.com" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/:username=n3oltd" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/:_password=${{ inputs.azure-feed-token }}" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/:email=n3oltd@n3oltd.com" >> .npmrc; )
        done
      working-directory: ${{github.workspace}}
      env: 
        NODE_AUTH_TOKEN: ${{inputs.access-token}}

